//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dependent
    {
        public int DepId { get; set; }
        public Nullable<int> CitizenType { get; set; }
        public Nullable<int> DetailId { get; set; }
        public Nullable<int> MemberId { get; set; }
    }
}
