//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndvidualTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IndvidualTbl()
        {
            this.OrgChiefAdmins = new HashSet<OrgChiefAdmin>();
        }
    
        public int Id { get; set; }
        public string Fname { get; set; }
        public string LName { get; set; }
        public string MName { get; set; }
        public Nullable<int> Title { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> CountryOfBirth { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<decimal> IDNumber { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<decimal> HomeTelNo { get; set; }
        public Nullable<decimal> WorkTelNo { get; set; }
        public Nullable<decimal> CellularNo { get; set; }
        public string PrimeryEmail { get; set; }
        public string AlternativeEmail { get; set; }
        public string FacebookId { get; set; }
        public string Twitter { get; set; }
        public string ResidentialAdd { get; set; }
        public string PostalAdd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrgChiefAdmin> OrgChiefAdmins { get; set; }
    }
}
