//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SABenefitsEntities : DbContext
    {
        public SABenefitsEntities()
            : base("name=SABenefitsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dependent> Dependents { get; set; }
        public virtual DbSet<IndvidualTbl> IndvidualTbls { get; set; }
        public virtual DbSet<MasterType> MasterTypes { get; set; }
        public virtual DbSet<MasterValue> MasterValues { get; set; }
        public virtual DbSet<OrgChiefAdmin> OrgChiefAdmins { get; set; }
        public virtual DbSet<OrgTbl> OrgTbls { get; set; }
    }
}
